smakan/polls/urls.py
from django.urls import path, include
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('event/<int:pk>', views.event_detail, name='event_detail'),
    path('create_event', views.create_event, name='create_event'),
    path('create_location', views.create_location, name='create_location'),
    path('update/<int:pk>', views.update_event, name='update'),
    path('delete/<int:pk>', views.delete_event, name='delete'),
    path('register', views.register, name='register'),
    path('logout', views.sign_out, name='logout'),
    path('login', views.sign_in, name='login'),
]

smakan/smakan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

admin.site.site_header = "SMAKAN Administration"
admin.site.site_title = "By Dylan"
admin.site.index_title = "SMACC2's Makan App"

smakan/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Location(models.Model):
    name            = models.CharField(max_length=120, blank=False, unique=True)
    url             = models.URLField(max_length=500, blank=True)
    
    def __str__(self) -> str:
        return self.name

class Event(models.Model):
    location        = models.ForeignKey(Location, on_delete=models.CASCADE)
    creator         = models.ForeignKey(User, on_delete=models.CASCADE, related_name='event_creator')
    created_date    = models.DateTimeField(auto_now_add=True)
    voters          = models.ManyToManyField(User, blank=True, related_name='event_voters')
    note            = models.TextField(blank=True)
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.created_date <= now

    def get_voters(self):
        return [v.username for v in self.voters.all()]

    def __str__(self) -> str:
        return str(self.created_date)

smakan/polls/forms.py
from django import forms
from .models import Event, Location

class CreateEventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateEventForm, self).__init__(*args, **kwargs)
        self.fields['note'].widget.attrs = {
            'class': 'u-full-width', 
            'placeholder': 'This info will be displayed to other people.'
            }
        self.fields['location'].widget.attrs = {
            'class': 'u-full-width', 
            'placeholder': 'Choose from previously created'
            }
    class Meta:
        model = Event
        fields = ('location', 'note')
        labels = {
            'note': 'Extra Info',
            'location': 'Choose from a previous location'
        }

class CreateEventWithLocationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateEventWithLocationForm, self).__init__(*args, **kwargs)
        self.fields['note'].widget.attrs = {
            'class': 'u-full-width', 
            'placeholder': 'This info will be displayed to other people.'
            }
    class Meta:
        model = Event
        fields = ('note',)
        labels = {
            'note': 'Extra Info',
        }

class CreateLocationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateLocationForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {
            'class': 'u-full-width', 
            'placeholder': 'Where are we going?'
            }
        self.fields['url'].widget.attrs = {
            'class': 'u-full-width', 
            'placeholder': 'What\'s the Google maps / waze URL?'
            }
    class Meta:
        model = Location
        fields = '__all__'
        labels = {
            'name': 'Dinner Place Name',
            'url': 'URL',
        }

class UpdateEventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UpdateEventForm, self).__init__(*args, **kwargs)
        self.fields['note'].widget.attrs = {
            'class': 'u-full-width', 
            'placeholder': 'This info will be displayed to other people.'
            }
    class Meta:
        model = Event
        fields = ('note',)
        labels = {
            'note': 'Extra Info',
        }

class UpdateLocationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UpdateLocationForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {
            'class': 'u-full-width', 
            'placeholder': 'Where are we going?'
            }
        self.fields['url'].widget.attrs = {
            'class': 'u-full-width', 
            'placeholder': 'What\'s the Google maps / waze URL?'
            }
    class Meta:
        model = Location
        fields = '__all__'
        labels = {
            'name': 'Dinner Place Name',
            'url': 'URL',
        }

smakan/polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Count
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm 

from .models import Event, Location
from .forms import CreateEventForm, CreateEventWithLocationForm, CreateLocationForm, UpdateEventForm, UpdateLocationForm

def index(request):
    # Get recent events from model as a queryset ordered by number of voters
    recent_events_ids = [e.id for e in Event.objects.all() if e.was_published_recently()]
    filtered = Event.objects.filter(id__in=recent_events_ids)
    queryset = filtered.annotate(voter_count = Count('voters')).order_by('-voter_count')

    # Handle users who click 'Join'
    if request.method == "POST" and 'join' in request.POST and request.user.is_authenticated:
        event = Event.objects.get(pk=request.POST['event_id'])
        event.voters.add(request.user)
        messages.success(request, "Joined event!")
        return redirect('polls:event_detail', pk=request.POST['event_id'])
    # Handle users who click 'Exit'
    elif request.method == "POST" and 'exit' in request.POST and request.user.is_authenticated:
        event = Event.objects.get(pk=request.POST['event_id'])
        event.voters.remove(request.user)
        messages.success(request, "Exited event!")
        return redirect('polls:event_detail', pk=request.POST['event_id'])

    # Render page as usual
    return render(request, 'polls/index.html', context={'events' : queryset})


def event_detail(request, pk):
    # Get event model
    event = get_object_or_404(Event, pk=pk)
    
    # Handle actions on event detail view
    if request.method == "POST" and 'join' in request.POST and request.user.is_authenticated:
        event.voters.add(request.user)
        messages.success(request, "Joined event!")
        return redirect('polls:event_detail', pk=pk)
    elif request.method == "POST" and 'exit' in request.POST and request.user.is_authenticated:
        event.voters.remove(request.user)
        messages.success(request, "Exited event!")
        return redirect('polls:event_detail', pk=pk)
    elif request.user.is_authenticated == False:
        return redirect('polls:login')
    return render(request, 'polls/event_detail.html', context={'event': event})
    

def create_location(request):
    # Initialize Model forms under the create view
    location_form = CreateLocationForm()
    event_form = CreateEventForm()
    
    # Handle users who create events
    if request.user.is_authenticated:
        if request.method == "POST":
            location_form = CreateLocationForm(request.POST)
            event_form = CreateEventWithLocationForm(request.POST)

            # Handle multi-model form logic by avoiding commit and commiting after assignment
            if location_form.is_valid() and event_form.is_valid():
                a = location_form.save()
                b = event_form.save(commit=False)
                b.location = a 
                b.creator = request.user
                b.save()
                b.voters.add(request.user)
                messages.success(request, "Event successfully created!")
                return redirect('polls:index')
            else: 
                messages.info(request, "Location with that name already exists. Try another one?")
                return redirect('polls:create_location')
        # Handle default view for authenticated users
        else: 
            context = {
                'location_form': location_form,
                'event_form': event_form
            }
            return render(request, 'polls/create_location.html', context=context)
    else:
        return redirect('polls:login')

def create_event(request):
    # Initialize Model forms under the create view
    event_form = CreateEventForm()
    
    # Handle users who create events
    if request.user.is_authenticated:
        if request.method == "POST":
            event_form = CreateEventForm(request.POST)
            if event_form.is_valid():
                a = event_form.save(commit=False)
                a.creator = request.user
                a.save()
                a.voters.add(request.user)
                messages.success(request, "Event successfully created!")
                return redirect('polls:index')
            else: 
                messages.info(request, "Something went wrong. Please contact your website administrator.")
                return redirect('polls:index')
        # Handle default view for authenticated users
        else: 
            return render(request, 'polls/create_event.html', context={'event_form': event_form})
    else:
        return redirect('polls:login')

def update_event(request, pk):
    # Retrieve models and initialize form with model instances
    event = get_object_or_404(Event, pk=pk)
    location = get_object_or_404(Location, pk=event.location.id)
    event_form = UpdateEventForm(instance=event)
    location_form = UpdateLocationForm(instance=location)

    if request.user.is_authenticated:
        print(request.POST)
        if request.method == "POST" and 'edit' in request.POST:
            location_form = UpdateLocationForm(request.POST, instance=location)
            event_form = UpdateEventForm(request.POST, instance=event)

            if location_form.is_valid() and event_form.is_valid():
                location_form.save()
                event_form.save()
                messages.success(request, "Event edited successfully!")
                return redirect('polls:event_detail', pk=pk)
        # Redirect to delete view
        elif request.method == "POST" and 'delete' in request.POST:
            return redirect('polls:delete', pk=pk)
        else: 
            context = {
                'event': event,
                'location_form': location_form,
                'event_form': event_form,
            }
            return render(request, 'polls/update_event.html', context=context)
    else:
        return redirect('polls:login')

def delete_event(request, pk):
    # Retrieve object to be deleted
    event = get_object_or_404(Event, pk=pk)

    if request.user.is_authenticated:
        if request.method == "POST" and 'confirm' in request.POST:
            event.delete()
            messages.success(request, "Event deleted successfully!")
            return redirect('polls:index')
        elif request.method == "POST" and 'decline' in request.POST:
            return redirect('polls:update', pk=pk)
        else:
            return render(request, 'polls/delete_event.html', context={'event': event})
    else:
        return redirect('polls:login')


def register(request):
    # Handle user creation
    # TODO refactor to use model form
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "Welcome to Smakan!")
            return redirect('polls:index')
        else:
            messages.warning(request, "The account already exists.")
            return render(request, 'polls/register.html', {})
    elif request.user.is_authenticated == True:
        return redirect('polls:index')
    else:
        form = UserCreationForm()
        return render(request, 'polls/register.html', {})


def sign_in(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Welcome back!")
            return redirect('polls:index')
        elif user is None:
            messages.warning(request, "Wrong password.")
            return redirect('polls:login')
    elif request.user.is_authenticated == True:
        return redirect('polls:index')
    else:
        return render(request, 'polls/login.html', {})


def sign_out(request):
    if request.user.is_authenticated == True:
        logout(request)
    return render(request, 'polls/logout.html', {})

smakan/polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Skeleton CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'polls/normalize.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/skeleton.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/custom.css' %}"/>

    <!-- Emoji Favicon -->
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🍱</text></svg>">
    
    <!-- Templated page title -->
    <title>{% block title %}{% endblock title %} | smakan</title>
</head>

<body id="home-body" style="background-image: url('{% static 'polls/waves.svg' %}');">
    {% include 'polls/navbar.html' %}
    <div class="container">
        <div class="row" style="padding-top:3em">{% block hero %}{% endblock hero %}
        {% if messages %}
        <div class="example-grid docs-example">
            {% for message in messages %}
            <div class="column u-full-width" style="background-color: #EEB759;">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}
        </div>
        
        {% block content %}
        {% endblock content %}
    </div>
    <footer class="footer">
    <div class="row">
        <p class="mb-0" style="color: #33C3F0">Made with 💙 by Dylan</p>
    </div>
    </footer>
</body>
</html>

smakan/polls/templates/polls/create_event.html
{% extends 'polls/base.html' %}

{% block title %}

Add Suggestion

{% endblock title %}

{% block hero %}

<h1><strong>Add Dinner Suggestion</strong></h1>
<h5>Hi {{ user }}, where would you want to have dinner tonight?</h5>

{% endblock hero %}


{% block content %}
<div class="row row-card">
  <div class="column">
<form action="{% url 'polls:create_event' %}" method="POST">
    {% csrf_token %}
    {{ event_form.location.label_tag }}
    {{ event_form.location }}
    <p class="secondary"><i>Don't see your favourite dinner place? Create a new dinner location <a href="{% url 'polls:create_location' %}">here</a>.</i></p>
    {{ event_form.note.label_tag }}
    {{ event_form.note }}
    <input class="button-primary u-full-width" type="submit" value="Submit">
</form>
</div>
</div>
{% endblock content %}

smakan/polls/templates/polls/create_location.html
{% extends 'polls/base.html' %}

{% block title %}

Add Suggestion

{% endblock title %}

{% block hero %}

<h1><strong>Create Location</strong></h1>
<h5>Let's get everyone on board this new place!</h5>

{% endblock hero %}


{% block content %}
<div class="row row-card">
  <form action="{% url 'polls:create_location' %}" method="POST">
  {% csrf_token %}
  <div class="row">
      <div class="six columns">
      {{ location_form.name.label_tag }}
      {{ location_form.name }}
      </div>
      <div class="six columns">
      {{ location_form.url.label_tag }}
      {{ location_form.url }}
      </div>
    </div>
    <div class="row">
      {{ event_form.note.label_tag }}
      {{ event_form.note }}
      <input class="button-primary u-full-width" type="submit" value="Submit">
    </div>
  </form>
  <p class="secondary"><i>Changed your mind? Go <a href="{% url 'polls:create_event' %}">back</a> to select a dinner place.</i></p>
</div>
{% endblock content %}

smakan/polls/templates/polls/delete_event.html
{% extends 'polls/base.html' %}

{% block title %}

Delete

{% endblock title %}

{% block hero %}

<h1><strong>Deleting: {{ event.location.name }}</strong></h1>
<h5>Are you sure you want to delete this event?</h5>

{% endblock hero %}


{% block content %}
<div class="row row-card">
  <div class="column">
<form method="POST">
    {% csrf_token %}
    <input class="button button-primary u-full-width mb-0" name="confirm" type="submit" value="Yes">
  </form>
<form class="mb-0" method="POST">
    {% csrf_token %}
    <input class="button u-full-width mb-0" name="decline" type="submit" value="No">
  </form>
</div>
</div>
{% endblock content %}

smakan/polls/templates/polls/event_detail.html
{% extends 'polls/base.html' %}

{% block title %}

{{ event.location.name }}

{% endblock title %}

{% block hero %}

<h1><strong>{{ event.location.name }}</strong></h1>
<h5>Suggestion made by {{ event.creator.username }} at {{ event.created_date }}</h5>

{% endblock hero %}


{% block content %}

<div class="row">
    <div class="column">
      {% if event.location.url %}
      <a class="button button-primary" href="{{ event.location.url }}" target="_blank">Map link</a>
      {% endif %}
      {% if event.creator.id == user.id %}
      <a class="button" href="{% url 'polls:update' event.id %}">Edit</a>
      {% endif %}
    </div>
</div>
<div class="row row-card">
  <div class="column">
      {% if event.note %}
      <hr>
      <p class="secondary">Notes:</p>
      <p class="secondary">{{ event.note }}</p>
      <hr>
      {% endif %}

      {% if event.voters.all|length == 0%}
      <p>Oh no! Nobody's coming. Would you like to be the first?</p>
      {% else %}
      <p>Here's who will be going:</p>
      <ol>
        {% for v in event.get_voters %}
        <li>
          {{ v }}
        </li>
        {% endfor %}
      </ol>
      {% endif %}
      {% if user.username not in event.get_voters %}
      <form method="POST">
        {% csrf_token %}
        <input class="button button-primary" name="join" type="submit" value="Join Dinner">
      </form>
      {% else %}
      <form method="POST">
        {% csrf_token %}
        <input class="button" name="exit" type="submit" value="Exit Dinner">
      </form>
      {% endif %}
    </div>
</div>

{% endblock content %}

smakan/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block title %}

Let's-makan together!

{% endblock title %}

{% block hero %}

<div class="flexbox" style="align-content:center;">
  <h1><strong>Let's makan!</strong></h1>
</div>
<div class="flexbox" style="align-content:center;">
  <h5>Select a dinner place or create a new one:</h5>
  <a class="button" style="margin:4px" href="{% url 'polls:create_event' %}"><strong>Suggest</strong></a>
</div>

{% endblock hero %}


{% block content %}

<div class="row" style="padding-top:3em">
  <div class="column">
    {% if events %}
  <div class="flexbox">
    {% for event in events %}
    <div class="card">
      <a href="{% url 'polls:event_detail' event.id %}"><span class="card__link"></span></a>
      <p class="mb-0 secondary"><strong>#{{ forloop.counter }}</strong></p>
      <h3 class="mb-0"><strong>{{ event.location.name }}</strong></h3>
      <p class="mb-0 secondary"><i>suggested by {{ event.creator.username }}</i></p>
      {% if event.get_voters|length == 0 %}
        <p>Nobody's going! 😟</p>
      {% elif event.get_voters|length > 3 %}
        <p>Going: {{ event.get_voters.0 }}, {{ event.get_voters.1 }}, {{ event.get_voters.2 }}, and {{ event.get_voters|length|add:"-3" }} other{{ event.get_voters|length|add:"-3"|pluralize }}...</p>
      {% else %}
        <p>Going: {{ event.get_voters|join:", " }}</p>
      {% endif %}
      <div class="flexbox buttons">
        {% if user.is_authenticated and user.username not in event.get_voters %}
          <form style="margin-bottom:0px" method="POST">
            {% csrf_token %}
            <input type="hidden" id="event_id" name="event_id" value="{{ event.id }}">
            <input class="button button-primary card-button" name="join" type="submit" value="Join">
          </form>
        {% elif user.is_authenticated and user.username in event.get_voters %}
          <form style="margin-bottom:0px" method="POST">
            {% csrf_token %}
            <input type="hidden" id="event_id" name="event_id" value="{{ event.id }}">
            <input class="button card-button" name="exit" type="submit" value="Quit">
          </form>
        {% else %}
          <a class="button card-button" style="margin:4px" href="{% url 'polls:login' %}">Login to view</a>
        {% endif %}
        {% if user.is_authenticated and user == event.creator %}
          <a class="button card-button" href="{% url 'polls:update' event.id %}">Edit</a>
        {% endif %}
      </div>
    </div>
    {% endfor %}
    {% endif %}
</div>
</div>
</div>

{% endblock content %}

smakan/polls/templates/polls/login.html
{% extends 'polls/base.html' %}

{% block title %}

Login

{% endblock title %}

{% block hero %}

<h1><strong>Login</strong></h1>
<h5>Log in to access or create dinner suggestions.</h5>

{% endblock hero %}


{% block content %}
<div class="row row-card">
<form method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="six columns">
        <label for="username">Name</label>
        <input class="u-full-width" type="text" placeholder="St. Augustine" id="username" name="username">
      </div>
      <div class="six columns">
          <label for="password">Password PIN (4 digits)</label>
          <input class="u-full-width" type="password" id="password" name="password" title="4-digit Pin" pattern="[0-9]{4}" placeholder="1234" maxlength="4">
      </div>
    </div>
    <input class="button-primary" type="submit" value="Login">
  </form>
  <p>Don't have an account? Create one <a href="{% url 'polls:register' %}">here</a>.</p>
</div>
{% endblock content %}

smakan/polls/templates/polls/logout.html
{% extends 'polls/base.html' %}

{% block title %}

Logout

{% endblock title %}

{% block hero %}

<h1><strong>Logout</strong></h1>
<h5>You're out. Go home?</h5>

{% endblock hero %}


{% block content %}

<a class="button button-primary" href="{% url 'polls:index'%}">Yeah</a>
<a class="button" href="{% url 'polls:index'%}">Nah</a>
{% endblock content %}

smakan/polls/templates/polls/navbar.html
<nav class="navbar">
    <div class="container" style="display:flex;">
        <a class="navbar-link" style="margin-right:auto;" href="{% url 'polls:index' %}">🍱</a>
        <ul class="navbar-list">
            {% if user.is_authenticated %}
            <li class="navbar-item">
                <p class="navbar-link">Hello, {{ user.username }}</p>
            </li>
            <li class="navbar-item">
                <a class="navbar-link" href="{% url 'polls:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="navbar-item">
                <p class="navbar-link">Hello, guest</p>
            </li>
            <li class="navbar-item">
                <a class="navbar-link" href="{% url 'polls:login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

smakan/polls/templates/polls/register.html
{% extends 'polls/base.html' %}

{% block title %}

Register

{% endblock title %}

{% block hero %}

<h1><strong>Registration</strong></h1>
<h5>Let's get you set up.</h5>

{% endblock hero %}


{% block content %}

<div class="row row-card">
<form action="{% url 'polls:register' %}" method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="column">
        <label for="username">Name</label>
        <input class="u-full-width" type="text" placeholder="Thomas Aquinas" id="username" name="username">
      </div>
    </div>
    <div class="row">
        <div class="six columns">
            <label for="password1">Password PIN (4 digits)</label>
            <input class="u-full-width" type="password" id="password1" name="password1" title="4-digit Pin" pattern="[0-9]{4}" placeholder="1234" maxlength="4">
        </div>
        <div class="six columns">
            <label for="password2">Confirm Password PIN (4 digits)</label>
            <input class="u-full-width" type="password" id="password2" name="password2" title="4-digit Pin" pattern="[0-9]{4}" placeholder="1234" maxlength="4">
        </div>
    </div>
    <input class="button-primary" type="submit" value="Register">
  </form>
  <p>Already have an account? Log in <a href="{% url 'polls:login' %}">here</a>.</p>
</div>
{% endblock content %}

smakan/polls/templates/polls/update_event.html
{% extends 'polls/base.html' %}

{% block title %}

Update

{% endblock title %}

{% block hero %}

<h1><strong>Edit: {{ event.location.name }}</strong></h1>
<h5>Hey {{ user }}, let's edit your suggestion...</h5>

{% endblock hero %}


{% block content %}
<div class="row row-card">
  <div class="column">
<form method="POST">
    {% csrf_token %}
    {{ location_form.as_table }}
    {{ event_form.as_table }}
    <input class="button button-primary u-full-width mb-0" name="edit" type="submit" value="Save">
  </form>
<form class="mb-0" method="POST">
    {% csrf_token %}
    <input class="button u-full-width mb-0" name="delete" type="submit" value="Delete">
  </form>
</div>
</div>
{% endblock content %}